insert into users(id, nickname, first_name, last_name, email, profile_image_url, gender, date_of_birth, height, weight, mbti, healthcare_type, stress_point, is_smoking, is_alcohol, created_at, updated_at) values (0, '홍길동!!!', '길동', '홍', 'test@test.com', '', 'MALE', '2023-01-01', 180, 70, 'INTJ', 'HEALTH', 0, false, false, '2023-01-01T00:00:00', '2023-01-01T00:00:00');

insert into daily_health_messages(id, type, personality, content) values(1, 'EXERCISE', 'INTROVERSION', 'EXERCISE INTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(2, 'EXERCISE', 'EXTROVERSION', 'EXERCISE EXTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(3, 'EXERCISE', 'ALL', 'EXERCISE ALL message');
insert into daily_health_messages(id, type, personality, content) values(4, 'STRESS', 'INTROVERSION', 'STRESS INTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(5, 'STRESS', 'EXTROVERSION', 'STRESS EXTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(6, 'STRESS', 'ALL', 'STRESS ALL message');
insert into daily_health_messages(id, type, personality, content) values(7, 'HEALTH_GOAL', 'INTROVERSION', 'HEALTH_GOAL INTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(8, 'HEALTH_GOAL', 'EXTROVERSION', 'HEALTH_GOAL EXTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(9, 'HEALTH_GOAL', 'ALL', 'HEALTH_GOAL ALL message');
insert into daily_health_messages(id, type, personality, content) values(10, 'PROGRESS', 'INTROVERSION', 'PROGRESS INTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(11, 'PROGRESS', 'EXTROVERSION', 'PROGRESS EXTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(12, 'PROGRESS', 'ALL', 'PROGRESS ALL message');
insert into daily_health_messages(id, type, personality, content) values(13, 'FOOD', 'INTROVERSION', 'FOOD INTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(14, 'FOOD', 'EXTROVERSION', 'FOOD EXTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(15, 'FOOD', 'ALL', 'FOOD ALL message');
insert into daily_health_messages(id, type, personality, content) values(16, 'LIFE_STYLE', 'INTROVERSION', 'LIFE_STYLE INTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(17, 'LIFE_STYLE', 'EXTROVERSION', 'LIFE_STYLE EXTROVERSION message');
insert into daily_health_messages(id, type, personality, content) values(18, 'LIFE_STYLE', 'ALL', 'LIFE_STYLE ALL message');

insert into activities(id, name, symptom) values (1, 'TEST_ACTIVITY_1', 'LETHARGIC');
insert into activities(id, name, symptom) values (2, 'TEST_ACTIVITY_2', 'LETHARGIC');
insert into activities(id, name, symptom) values (3, 'TEST_ACTIVITY_3', 'LETHARGIC');
insert into activities(id, name, symptom) values (4, 'TEST_ACTIVITY_4', 'LETHARGIC');
insert into activities(id, name, symptom) values (5, 'TEST_ACTIVITY_5', 'LETHARGIC');
insert into activities(id, name, symptom) values (6, 'TEST_ACTIVITY_6', 'LETHARGIC');
insert into activities(id, name, symptom) values (7, 'TEST_ACTIVITY_7', 'LETHARGIC');
insert into activities(id, name, symptom) values (8, 'TEST_ACTIVITY_8', 'LETHARGIC');
insert into activities(id, name, symptom) values (9, 'TEST_ACTIVITY_9', 'LETHARGIC');
insert into activities(id, name, symptom) values (10, 'TEST_ACTIVITY_10', 'LETHARGIC');

insert into activity_mbti(id, mbti, activity_id) values (1, 'INTJ', 1);
insert into activity_mbti(id, mbti, activity_id) values (2, 'INFJ', 1);
insert into activity_mbti(id, mbti, activity_id) values (3, 'INTP', 1);
insert into activity_mbti(id, mbti, activity_id) values (4, 'INTJ', 2);
insert into activity_mbti(id, mbti, activity_id) values (5, 'INFJ', 2);
insert into activity_mbti(id, mbti, activity_id) values (6, 'INTP', 2);
insert into activity_mbti(id, mbti, activity_id) values (7, 'INTJ', 3);
insert into activity_mbti(id, mbti, activity_id) values (8, 'INFJ', 3);
insert into activity_mbti(id, mbti, activity_id) values (9, 'INTP', 3);
insert into activity_mbti(id, mbti, activity_id) values (10, 'INTJ', 4);
insert into activity_mbti(id, mbti, activity_id) values (11, 'INFJ', 4);
insert into activity_mbti(id, mbti, activity_id) values (12, 'INTP', 4);
insert into activity_mbti(id, mbti, activity_id) values (13, 'INTJ', 5);
insert into activity_mbti(id, mbti, activity_id) values (14, 'INFJ', 5);
insert into activity_mbti(id, mbti, activity_id) values (15, 'INTP', 5);
insert into activity_mbti(id, mbti, activity_id) values (16, 'ESTJ', 6);
insert into activity_mbti(id, mbti, activity_id) values (17, 'ESFJ', 6);
insert into activity_mbti(id, mbti, activity_id) values (18, 'ESTP', 6);
insert into activity_mbti(id, mbti, activity_id) values (19, 'ESTJ', 7);
insert into activity_mbti(id, mbti, activity_id) values (20, 'ESFJ', 7);
insert into activity_mbti(id, mbti, activity_id) values (21, 'ESTP', 7);
insert into activity_mbti(id, mbti, activity_id) values (22, 'ESTJ', 8);
insert into activity_mbti(id, mbti, activity_id) values (23, 'ESFJ', 8);
insert into activity_mbti(id, mbti, activity_id) values (24, 'ESTP', 8);
insert into activity_mbti(id, mbti, activity_id) values (25, 'ESTJ', 9);
insert into activity_mbti(id, mbti, activity_id) values (26, 'ESFJ', 9);
insert into activity_mbti(id, mbti, activity_id) values (27, 'ESTP', 9);
insert into activity_mbti(id, mbti, activity_id) values (28, 'ESTJ', 10);
insert into activity_mbti(id, mbti, activity_id) values (29, 'ESFJ', 10);
insert into activity_mbti(id, mbti, activity_id) values (30, 'ESTP', 10);

insert into user_activities(id, user_id, activity_id) values (0, 0, 1);
insert into stress_goals(id, accomplish_rate) values (0, 0.0);
update users set stress_goal_id = 0 where id = 0;
